---
- name: install packages specific to the ansible server
  apt: pkg={{ item }} state=latest
  with_items:
    - gmetad
    - ganglia-webfrontend

- name: configure gmetad
  template: src=etc/ganglia/gmetad.conf.j2 dest=/etc/ganglia/gmetad.conf owner=root group=root mode=0444
  notify:
  - restart gmetad

- name: ensure gmetad is running
  service: name=gmetad pattern=gmetad state=started
