#!/bin/bash

ALL_KERNELS=$(ls /boot/initrd.img-3.2.0-*)
OLD_KERNELS=$(for kernel in $ALL_KERNELS ; do echo "linux-image${kernel##*img}" | grep -v $(uname -r) ; done | head -n -1 | tr "\n" " ")

if [ -n "$OLD_KERNELS" ]; then
    apt-get -y remove $OLD_KERNELS
    update-grub
fi

