---
- name: change default editor for root
  tags: misc
  lineinfile: dest=/root/.bashrc line="export VISUAL=/usr/bin/vim" state=present

- name: disable hashing of ssh known hosts
  tags: misc
  lineinfile: dest=/etc/ssh/ssh_config regexp="^.*HashKnownHosts.*$" line="    HashKnownHosts no"

- name: get gnome setting for volumes-visible
  tags: misc
  command: gsettings get org.gnome.nautilus.desktop volumes-visible
  register: volumesvisible 

- name: get gnome setting for trash-icon-visible
  tags: misc
  command: gsettings get org.gnome.nautilus.desktop trash-icon-visible
  register: trashiconvisible

- name: set gnome setting for volumes-visible
  tags: misc
  command: gsettings set org.gnome.nautilus.desktop volumes-visible
  when: volumesvisible.stdout != "true"

- name: set gnome setting for trash-icon-visible
  tags: misc
  command: gsettings set org.gnome.nautilus.desktop trash-icon-visible
  when: trashiconvisible.stdout != "true"

- name: gnome settings
  tags: misc
  copy: src=usr/share/glib-2.0/schemas/20_danuser.gschema.override dest=/usr/share/glib-2.0/schemas/20_danuser.gschema.override owner=root group=root mode=0444
