---
- name: create /usr/local/MATLAB
  tags: matlab
  file: path=/usr/local/MATLAB owner=root group=root mode=0755 state=directory

- name: synchronize matlab from danuser-wkstn1
  tags: matlab
  synchronize: src=/home/precise/usr/local/MATLAB/{{ item }}/ dest=/usr/local/MATLAB/{{ item }}/ archive=yes
  with_items: keep_matlab_versions

- name: create symlink for matlab
  tags: matlab
  file: src=/usr/local/MATLAB/{{ item }}/bin/matlab dest=/usr/local/bin/matlab_{{ item|lower }} owner=root group=root state=link
  with_items: keep_matlab_versions

- name: template desktop shortcut to /usr/share/applications/
  tags: matlab
  template: src=usr/share/applications/mathworks-matlab.desktop.j2 dest=/usr/share/applications/mathworks-matlab{{ item }}.desktop owner=root group=root mode=0444
  with_items: keep_matlab_versions

#- name: configure desktop shortcut
#  tags: matlab
#  lineinfile: dest=/usr/share/applications/mathworks-matlab{{ item }}.desktop regexp={{ item.regexp }} line="{{ item.line }}"
#  with_items:
#    - { regexp: '^Name', line: 'Name=Matlab {{ item }}' }
#    - { regexp: '^Comment', line: 'Comment=Matlab {{ item }}' }
#    - { regexp: '^TryExec', line: 'TryExec=/usr/local/MATLAB/{{ item }}/bin/matlab' }
#    - { regexp: '^Exec', line: 'Exec=/usr/local/MATLAB/{{ item }}/bin/matlab -desktop' }
#  
