---
- name: rsync matlab from danuser-wkstn1
  tags: matlab
  command: rsync -a danuser-wkstn1::precise/usr/local/MATLAB/{{ vers }}/ /usr/local/MATLAB/{{ vers }}/

- name: copy desktop shortcut to /usr/local
  tags: matlab
  copy: src=/home/precise/usr/local/MATLAB/mathworks-matlab{{ vers }}.desktop dest=/usr/local/MATLAB/mathworks-matlab{{ vers }}.desktop owner=root group=root mode=644

- name: copy desktop shortcut to /usr/share/applications/
  tags: matlab
  copy: src=/home/precise/usr/local/MATLAB/mathworks-matlab{{ vers }}.desktop dest=/usr/share/applications/mathworks-matlab{{ vers }}.desktop owner=root group=root mode=644

- name: create symlink for matlab
  tags: matlab
  file: src=/usr/local/MATLAB/{{ vers }}/bin/matlab dest=/usr/local/bin/matlab_{{ vers|lower }} owner=root group=root state=link
