---
- name: delete symlink
  tags: matlab
  file: path=/usr/local/bin/matlab_{{ item|lower }} state=absent
  with_items: remove_matlab_versions

- name: delete desktop shortcut
  tags: matlab
  file: path=/usr/share/applications/mathworks-matlab{{ item }}.desktop state=absent
  with_items: remove_matlab_versions

- name: delete files
  tags: matlab
  file: path=/usr/local/MATLAB/{{ item }}/ state=absent
  with_items: remove_matlab_versions
