---
- hosts: all
  gather_facts: yes
  user: root
  tasks:
    - name: delete symlink
      command: rm -f /usr/local/bin/matlab_r2011b
      register: command_result
    - name: delete desktop shortcut
      command: rm -f /usr/share/applications/mathworks-matlabR2011b.desktop
    - name: delete files
      command: rm --one-file-system -rf /usr/local/MATLAB/R2011b/
